# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.9.1 on 2016-01-06 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 1.9.1 on 2016-01-06 17:00
from __future__ import unicode_literals

from django.db import migrations, models
>>>>>>> master


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=5)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=6)),
                ('location', models.CharField(blank=True, default='', max_length=1)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Fund')),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=2)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Fund')),
=======
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
>>>>>>> master
            ],
        ),
    ]
