# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_named_account_fund_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='budget.Fund'),
        ),
    ]
