# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_funds_have_subs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
